support client_credentials grant_type
thefrontside/simulacrum pull request #230
Opened 2022-11-17 23:10 UTC by jbolda

## Motivation

Add specific support for additional `grant_type`s. This was required to enable m2m token use. Note, this flow does not appear to run the rules, so the return logic is slightly adjusted to suit.

2022-11-18 09:54 UTC, dagda1 requested changes

2022-11-18 14:45 UTC, jbolda commented on packages/auth0/src/handlers/auth0-handlers.ts
>        if (grant_type === 'password') {
Yea, that makes a lot of sense. 👍

2022-11-18 15:03 UTC, jbolda commented on packages/auth0/src/handlers/auth0-handlers.ts
> +      } else if (grant_type === 'client_credentials') {
Yea I can see that. I suspect that we will end up fleshing out these `grant_type`s more to cover them all. I am tempted to say that maybe it makes sense to do it at that time?

2022-11-18 15:09 UTC, dagda1 commented on packages/auth0/src/handlers/auth0-handlers.ts
> +      } else if (grant_type === 'client_credentials') {
it's up to you but I would do it now and you'll save time in the long run or else it'll be really hard to tell what is going on.

I could do it in another PR if you want when you are finished

2022-11-18 22:54 UTC, jbolda commented on packages/auth0/src/handlers/auth0-handlers.ts
> +      } else if (grant_type === 'client_credentials') {
Might as well do it as part of this PR then. I can work on that on Monday.

2022-11-23 03:33 UTC, jbolda commented on packages/auth0/src/handlers/auth0-handlers.ts
> +      } else if (grant_type === 'client_credentials') {
I feel pretty good about the refactor: https://github.com/thefrontside/simulacrum/pull/230/commits/134e5fe1ef2bd0fae316b0b23b7a2181e0148e73

2022-11-23 14:47 UTC, dagda1 approved these changes

2022-11-28 16:33 UTC, merged